# handler
apiVersion: "config.istio.io/v1alpha2"
kind: jwtcheck
metadata:
  name: unexpiredtoken
  namespace: istio-system
spec: 
  file_path: "out.txt"
  auth_private_key: "asfasdf"
---
# instance
apiVersion: "config.istio.io/v1alpha2"
kind: authorization
metadata:
  name: authinfo
  namespace: istio-system
spec:
  subject:
    user: source.user | ""
    groups: ""
    properties:
      app: source.labels["app"] | ""
      version: source.labels["version"] | ""
      namespace: source.namespace | ""
  action:
    namespace: destination.namespace | ""
    service: destination.service | ""
    method: request.method | ""
    path: request.path | ""
    properties:
      app: destination.labels["app"] | ""
---
  # rule
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: mixerdenysome
  namespace: istio-system
spec:
  match: "true"
  actions:
  - handler: unexpiredtoken.jwtcheck
    instances:
    - authinfo.authorization
